# This is a basic workflow to help you get started with Actions

name: Main Orchestrator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test_matrix:
    name: 'Create list of changed modules blah'
    uses: amarjeetbatra/github_actions/.github/workflows/test_matrix.yml@main
  
  plan:
    needs: [test_matrix]
    name: 'Plan'
    uses: amarjeetbatra/github_actions/.github/workflows/plan.yml@main
    with:
      matrix: "${{ needs.test_matrix.outputs.matrix }}"
  
