name: Reusable workflow - Plan

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  plan:
    name: 'Plan'
    runs-on: self-hosted
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: ${{fromJson(inputs.matrix)}}
    steps:
      
      # Runs a single command using the runners shell
      - name: Under Plan : Run a one-line script
        run: echo Hello, world PLAN !

      # Runs a set of commands using the runners shell
      - name: Under Plan : Run a multi-line script
        run: |
          echo Add other actions to build PLAN,
          echo test, and deploy your project PLAN.
