name: Test matrix output workflow

on:
  workflow_call:
    outputs:
      matrix:
        description: "List of modules"
        value: ${{ jobs.added_modified.outputs.matrix }}

jobs:
  added_modified:
    name: 'Create list of changed modules'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: get parent directory and set matrix
        id: set-matrix
        run: |
          #tg_dir=""
          tg_dir="{\"node\":[10, 12, 13, 15]}"
          echo "::set-output name=matrix::$tg_dir"
